### ISSUE TITLE
关于刷课无法跳过已看过的视频

### ISSUE THREAD

**Issue by Elaina-Offcial** [RHzzz666/yuketang_for_SUCT#1]
经过多次复现，长江雨课堂目前使用该脚本刷课时，刷新页面之后如果并非手动点击展开，由脚本展开列表则会出现所有课程都显示未观看的现象，故重复刷取第一课，且看完该视频后无法正常返回上级进入下一节课。

**Comment by RHzzz666** [comment]
由于本人已无未观看课程，故无法进行测试，可自行修改源码进行适配
